### PR TITLE
Unicite identifiants label

### LINKED ISSUE #4: [Namespaces] Ajouter un contrôle d'unicité pour l'ensemble des identifiants des classes et des propriétés d'un espace de noms [1020]
Pour permettre l'utilisation d'URI de la forme https://ontome.net/ns/label/id valable pour les classes **et** les propriétés d'un espace de noms :

* Ajouter un contrôle d'unicité des identifiants des classes et des propriétés par espace de noms lors de la création et de la modification manuelle de l'identifiant d'une classe ou d'une propriété.

### PR DESCRIPTION
**Pull request by perrauda**
Resolves #4

### CODE REVIEW

**Comment by perrauda** [comment]
Au lieu de: The identifier must be unique. Please enter another one.
Modifier: The identifier must be unique within the same namespace. Please enter a different one.

**Comment by perrauda** [comment]
Au lieu de: This label is already used by another project, please enter another one
Modifier: This label is already used by another project, please enter a different one

**Comment by perrauda** [comment]
Checker l'erreur quand on créé un namespace
Conditions de test: avoir repris un nom de projet en nom de namespace root.

**Review by valamercery — APPROVED** [review]
Testé, conforme

**Review by dferhod — APPROVED** [review]
Review OK

**Pull request merged**
